version: '3.8'
services:
  mq:
    image: ibmcom/mq:latest
    container_name: ibm_mq
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
      - MQ_ADMIN_USER=admin
      - MQ_ADMIN_PASSWORD=passw0rd
    ports:
      - "1414:1414"
      - "9443:9443"
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"